---
addons:
  postgresql: "11.2"
services:
  - postgresql
sudo: false
language: ruby
cache: bundler
env:
  - RAILS_ENV=test
before_install:
  - gem update --system
  - gem install bundler
script:
  - bin/rake db:test:prepare
  - bin/rake rspec --order rand