---
addons:
  postgresql: "9.6"
services:
  - postgresql
sudo: false
language: ruby
cache: bundler
env:
  - RAILS_ENV=test
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake rspec